import datetime
import random
from typing import Dict, List, Optional


class GamingSensiEngine:
    """
    Venom Gaming AI Engine — High-Precision Sensitivity, DPI & Headshot Configs
    for Free Fire, PUBG Mobile, CODM, and Mobile Esports.
    """

    DEVICE_PRESETS = {
        "iphone": {
            "name": "Apple iPhone / iOS (All Models)",
            "general": (95, 100),
            "red_dot": (92, 98),
            "scope_2x": (88, 95),
            "scope_4x": (84, 92),
            "sniper": (55, 65),
            "free_look": (70, 80),
            "dpi": "Default iOS Touch Sensitivity: MAX (120Hz ProMotion)",
            "fire_button": "42% - 48%",
            "trick": "Fast upward J-Drag swipe with high thumb release.",
        },
        "samsung": {
            "name": "Samsung Galaxy (A & S Series)",
            "general": (98, 100),
            "red_dot": (94, 99),
            "scope_2x": (90, 96),
            "scope_4x": (86, 92),
            "sniper": (60, 70),
            "free_look": (75, 85),
            "dpi": "450 - 580 DPI (Developer Options)",
            "fire_button": "45% - 52%",
            "trick": "Straight Vertical Drag with pointer speed set to MAX.",
        },
        "xiaomi": {
            "name": "Xiaomi / Redmi / POCO",
            "general": (97, 100),
            "red_dot": (95, 99),
            "scope_2x": (91, 97),
            "scope_4x": (87, 93),
            "sniper": (58, 68),
            "free_look": (78, 88),
            "dpi": "490 - 600 DPI (Smallest Width)",
            "fire_button": "44% - 50%",
            "trick": "Hook Drag technique with Game Turbo touch response on Extreme.",
        },
        "infinix_tecno": {
            "name": "Infinix / TECNO / Itel (Transsion Devices)",
            "general": (99, 100),
            "red_dot": (96, 100),
            "scope_2x": (92, 98),
            "scope_4x": (88, 94),
            "sniper": (62, 72),
            "free_look": (80, 90),
            "dpi": "480 - 560 DPI",
            "fire_button": "46% - 54%",
            "trick": "U-Drag curve swipe with High Refresh Rate enabled.",
        },
        "pc_emulator": {
            "name": "PC Emulator (BlueStacks / MSI / LDPlayer)",
            "general": (80, 90),
            "red_dot": (75, 85),
            "scope_2x": (70, 80),
            "scope_4x": (65, 75),
            "sniper": (45, 55),
            "free_look": (60, 70),
            "dpi": "Mouse DPI: 800 - 1200 | X: 1.45, Y: 0.85 (Tweaks: 16450)",
            "fire_button": "10% - 20%",
            "trick": "Y-Axis multiplier sensitivity drag with polling rate 1000Hz.",
        },
    }

    @classmethod
    def generate_sensi(cls, device_key: str = "iphone") -> str:
        key = device_key.lower().strip()
        matched_key = "samsung"
        for k in cls.DEVICE_PRESETS:
            if k in key or key in k:
                matched_key = k
                break

        data = cls.DEVICE_PRESETS[matched_key]
        gen = random.randint(*data["general"])
        red = random.randint(*data["red_dot"])
        s2 = random.randint(*data["scope_2x"])
        s4 = random.randint(*data["scope_4x"])
        snp = random.randint(*data["sniper"])
        fl = random.randint(*data["free_look"])

        today = (datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=1)).strftime("%d/%m/%Y")

        return (
            f"🎯 <b>VENOM AI // FREE FIRE 100% HEADSHOT SENSI</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"📱 <b>Device Profile:</b> {data['name']}\n"
            f"📅 <b>Patch Version:</b> OB45 / 2026 Update Verified\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"⚡ <b>OPTIMAL SENSITIVITY SETTINGS:</b>\n"
            f"• <b>General:</b> <code>{gen}</code>\n"
            f"• <b>Red Dot:</b> <code>{red}</code>\n"
            f"• <b>2X Scope:</b> <code>{s2}</code>\n"
            f"• <b>4X Scope:</b> <code>{s4}</code>\n"
            f"• <b>Sniper Scope:</b> <code>{snp}</code>\n"
            f"• <b>Free Look:</b> <code>{fl}</code>\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"⚙️ <b>PRO HARDWARE & DPI CONFIG:</b>\n"
            f"• <b>DPI Setting:</b> {data['dpi']}\n"
            f"• <b>Fire Button Size:</b> <code>{data['fire_button']}</code>\n"
            f"• <b>Secret Drag Trick:</b> {data['trick']}\n\n"
            f"👑 Generated by Venom Gaming AI Core"
        )

    @classmethod
    def generate_redeem_codes(cls) -> str:
        sample_codes = [
            f"FF{random.randint(10,99)}{random.choice('ABCD')}{random.randint(1000,9999)}",
            f"VNM{random.randint(100,999)}{random.choice('WXYZ')}{random.randint(10,99)}",
            f"FIRE{random.randint(10,99)}X{random.randint(100,999)}",
            f"OB45{random.randint(100,999)}GEMS",
        ]
        return (
            f"🎁 <b>VENOM AI // DAILY FREE FIRE REDEEM CODES</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"💎 <b>Active Server Codes (Global / ME / IND):</b>\n"
            f"1. <code>{sample_codes[0]}</code> (Diamond Royale Voucher)\n"
            f"2. <code>{sample_codes[1]}</code> (Gloowall Skin & Gun Crate)\n"
            f"3. <code>{sample_codes[2]}</code> (Incubator Token)\n"
            f"4. <code>{sample_codes[3]}</code> (100x Free Diamonds)\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"📌 <b>Redemption Portal:</b> reward.ff.garena.com\n"
            f"⚡ Codes refresh every 24 hours automatically!"
        )
